<a href="https://colab.research.google.com/github/CookieNtoo/TestCode99/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/refs/heads/main/Data/phishing_dataset.csv', delimiter=',')

In [13]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  fosforlumarket.com        0        0           1          3            0   
1      hutoknepper.de        0        0           0          0            0   
2   nguyentandung.org        0        0           1          1            0   
3        torcache.net        0        0           1          2            0   
4    maybank2u.com.my        0        0           1          4            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        1              0           0            1           0   
1             0        0              0           0            1           1   
2             0        0              0           0            0           0   
3             0        0              0           0            0           1   
4             0        0              0           1            1           1   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           0       0           0            1             0      1  
1           1       0           0            1             0      1  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           1       0           0            1             0      0

In [15]:
X = data.drop(['Domain', 'Label'], axis=1)

In [16]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          3            0             0   
1        0        0           0          0            0             0   
2        0        0           1          1            0             0   
3        0        0           1          2            0             0   
4        0        0           1          4            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        1              0           0            1           0           0   
1        0              0           0            1           1           1   
2        0              0           0            0           0           1   
3        0              0           0            0           1           1   
4        0              0           1            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [17]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [19]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [21]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.79
Precision: 0.8106097737553066
Recall: 0.79
F1 Score: 0.7857677749360614
Confusion Matrix:
[[1410  118]
 [ 512  960]]

SVC Metrics:
Accuracy: 0.8276666666666667
Precision: 0.8595744220617495
Recall: 0.8276666666666667
F1 Score: 0.8231595817018762
Confusion Matrix:
[[1495   33]
 [ 484  988]]

RandomForestClassifier Metrics:
Accuracy: 0.8563333333333333
Precision: 0.8638811736202803
Recall: 0.8563333333333333
F1 Score: 0.8553477258881114
Confusion Matrix:
[[1423  105]
 [ 326 1146]]

MLPClassifier Metrics:
Accuracy: 0.8483333333333334
Precision: 0.8656629134590438
Recall: 0.8483333333333334
F1 Score: 0.846138131309793
Confusion Matrix:
[[1466   62]
 [ 393 1079]]

KNeighborsClassifier Metrics:
Accuracy: 0.8476666666666667
Precision: 0.8604122142018574
Recall: 0.8476666666666667
F1 Score: 0.8459783922822535
Confusion Matrix:
[[1443   85]
 [ 372 1100]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8556666666666667
Precision: 0.8643921750333559
Recall

In [22]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.856333   0.863881  0.856333  0.855348
5  DecisionTreeClassifier  0.855667   0.864392  0.855667  0.854542
3           MLPClassifier  0.848333   0.865663  0.848333  0.846138
4    KNeighborsClassifier  0.847667   0.860412  0.847667  0.845978
1                     SVC  0.827667   0.859574  0.827667  0.823160
0      LogisticRegression  0.790000   0.810610  0.790000  0.785768
